export const typeFilter = {
  countryId: "countryId",
  countries: "countries",
  annuities: "annuities",
  published: "published",
  deleted: "deleted",
  sectors: "sectors",
  typologies: "typologies",
  locations: "locations",
  minimis: "minimis",
  status: "status",
  bftypes: "bftypes",
  sources: "sources",
  grantTypeInsert: "grantTypeInsert",
  category: "category",
  interest: "interest",
  rangePublicationDate: "rangePublicationDate",
  rangeCreatedDate: "rangeCreatedDate",
  targetSectors: "targetSectors",
}